### ISSUE TITLE
ImageNet pre-train and cityscapes training settings

### ISSUE THREAD

**Issue by Asthestarsfalll** [YihengZhang-CV/LPS-Net#5]
I'm wondering that did the miou score reported by table 5 in the paper use the ImageNet pre-trained?
And can you provide the exact training settings of ImageNet pre-train and cityscapes, including but not limited to data augments、optimizer settings and so on.
Thank you in advance!

**Comment by xiaoer666** [comment]
兄弟，你复现了吗

**Comment by Asthestarsfalll** [comment]
> 兄弟，你复现了吗

精度差几个点左右
